# Generated by Django 2.1.5 on 2019-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomNum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomnum',
            name='randomNum',
            field=models.FloatField(default=0.4837307565632363),
        ),
    ]
