# Generated by Django 2.1.5 on 2019-01-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomNum', '0002_randomnum_randomnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomnum',
            name='randomNum',
        ),
    ]
