# Generated by Django 2.1.5 on 2019-01-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomNum', '0003_remove_randomnum_randomnum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randomnum',
            options={'managed': False},
        ),
    ]
