# Generated by Django 2.1.5 on 2019-01-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomNum', '0004_auto_20190113_1605'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='randomnum',
            table='random_num',
        ),
    ]
